# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

your_function <- function(m) {
    .Call('_MemRBC_your_function', PACKAGE = 'MemRBC', m)
}

SRC_GEMINI_get_cotan_Laplacian_cxx <- function(mesh) {
    .Call('_MemRBC_SRC_GEMINI_get_cotan_Laplacian_cxx', PACKAGE = 'MemRBC', mesh)
}

